# -*- coding: utf-8 -*-
"""Data Visualisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JuFpqs7Q4HoRGoDwa3156a-Lhg0owPiv
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid", palette="pastel")

# 2️⃣ Load dataset
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

print("Dataset Shape:", df.shape)
print(df.head())

plt.figure(figsize=(7,4))
sns.histplot(df['total_bill'], kde=True, bins=20, color="skyblue")
plt.title("Distribution of Total Bill")
plt.xlabel("Total Bill ($)")
plt.ylabel("Count")
plt.show()

# Pie chart of Gender
plt.figure(figsize=(5,5))
df['sex'].value_counts().plot.pie(autopct='%1.1f%%', colors=['lightcoral','lightblue'])
plt.title("Gender Distribution")
plt.ylabel("")
plt.show()

plt.figure(figsize=(7,5))
sns.scatterplot(x="total_bill", y="tip", hue="sex", size="size", data=df, alpha=0.7)
plt.title("Total Bill vs Tip by Gender & Group Size")
plt.show()

# Boxplot: Tips by Day
plt.figure(figsize=(7,5))
sns.boxplot(x="day", y="tip", hue="sex", data=df)
plt.title("Tips by Day & Gender")
plt.show()

plt.figure(figsize=(7,5))
sns.violinplot(x="time", y="total_bill", data=df)
plt.title("Total Bill Distribution by Meal Time")
plt.show()

plt.figure(figsize=(6,4))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

# Average tip by day
avg_tips = df.groupby("day")["tip"].mean().reset_index()

plt.figure(figsize=(7,4))
sns.barplot(x="day", y="tip", data=avg_tips, palette="viridis")
plt.title("Average Tip by Day")
plt.ylabel("Average Tip ($)")
plt.show()
"""
Data Story:
- Saturday & Sunday are the busiest days with the highest total bills.
- Tips increase as the bill increases (positive correlation ~0.68).
- Male customers tend to give slightly higher tips than female customers.
- Dinner brings higher bills compared to lunch.
- Large groups (size > 4) don’t always give higher tips, showing tipping is not strictly proportional.

Decision Support:
- Restaurants should focus on weekend dinner service for maximum revenue.
- Encouraging larger groups doesn’t guarantee better tips.
- Training staff to upsell at dinner may increase total bills and tips.
"""