# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqOWHOoPzpz8bvP45vtvAz5Z-dZ2trsm
"""

import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

df.to_csv("tips.csv", index=False)

print(df.head())

import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)
df.to_csv("iris.csv", index=False)
print(df.head())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

"""
Questions to answer:
1. What are the data types and structure of this dataset?
2. Are there any missing values or duplicates?
3. How are numeric features distributed? Any outliers?
4. What is the relationship between total_bill, tip, and size?
5. Do male or female customers tip more on average?
6. Does smoking status affect tip amount?
"""

print("Dataset Shape:", df.shape)
print("\nFirst 5 Rows:\n", df.head())
print("\nData Info:\n")
print(df.info())
print("\nNumeric Summary:\n", df.describe())
print("\nCategorical Summary:\n", df.describe(include=['object']))

print("\nMissing Values:\n", df.isnull().sum())
print("\nDuplicate Rows:", df.duplicated().sum())

numeric_cols = ['total_bill', 'tip', 'size']
for col in numeric_cols:
    plt.figure()
    sns.histplot(df[col], kde=True, bins=20)
    plt.title(f"Distribution of {col}")
    plt.show()

for col in numeric_cols:
    plt.figure()
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot of {col}")
    plt.show()

for col in ['sex', 'smoker', 'day', 'time']:
    plt.figure()
    sns.countplot(x=col, data=df)
    plt.title(f"Count of {col}")
    plt.show()

plt.figure()
sns.scatterplot(x='total_bill', y='tip', hue='sex', data=df)
plt.title("Total Bill vs Tip by Gender")
plt.show()

plt.figure()
sns.boxplot(x='day', y='tip', hue='sex', data=df)
plt.title("Tip Amount by Day & Gender")
plt.show()

plt.figure(figsize=(6,4))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

print("\nAverage Tip by Gender:\n", df.groupby('sex')['tip'].mean())

print("\nAverage Tip by Smoker/Non-Smoker:\n", df.groupby('smoker')['tip'].mean())

"""
Observations:
- total_bill and tip are positively correlated (~0.68).
- Most tips are between 2 and 4 dollars.
- Friday has the fewest records; Saturday & Sunday are busiest.
- Male customers tip slightly more on average than female customers.
- No missing values or duplicates in this dataset.

Potential Data Issues:
- Small sample size for Friday could bias results.
- Outliers present in total_bill (very high bills).
"""